### ISSUE TITLE
Brute force detection has missing fields and does not show defaults

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1107]
1. Create a new realm
2. Go to Realm settings -> Security defenses -> Brute force detection
3. Click `Enabled`

Several fields are missing that exist in the old console and the [Marvel design](https://marvelapp.com/prototype/13g2f55e/screen/75843591).

The old console displays the default values for all the fields.  Also, `Minimum quick login wait` 
 should default to minutes instead of seconds for all fields except `Failure reset time`, which defaults to hours.

**Comment by edewit** [comment]
fixed in #1083

**Comment by edewit** [comment]
Some of this is fixed in #1083 just a question about the default values, when you say it should default to hours should the value be 1 hour? Or do you want the dropdown to not include minutes and seconds? Or 3rd option you only want the dropdown to be on hours and the input field empty and still have minutes and seconds?

**Comment by edewit** [comment]
@ssilvert seems that the old console also doesn't do any defaults:
![Screenshot from 2021-09-14 10-43-44](https://user-images.githubusercontent.com/51133/133225843-0f0c45aa-65bf-410b-991c-da8be9f31284.png)
