### ISSUE TITLE
User Fed: certificate-ldap-mapper has missing field

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#1484]
1. Go to User Federation --> LDAP --> LDAP Mappers
2. Create new mapper
3. Choose `certificate-ldap-mapper` as mapper type

Missing field: `Attribute default value`.  See old console.

**Comment by mfrances17** [comment]
This field was added as part of the fix for https://github.com/keycloak/keycloak-admin-ui/issues/1480. 

However, during testing, I noticed that when we changed the `Read Only` default to `ON` for `user-attribute-ldap-mapper` as part of the above fix, it is defaulting to `ON` for `certificate-ldap-mapper`, which is incorrect. The `Read Only` default for `user-attribute-ldap-mapper` is `ON`, but for `certificate-ldap-mapper` it should be `OFF`. So using this issue to fix that discrepancy.
