### ISSUE TITLE
navigation breaks on client details

### ISSUE THREAD

**Issue by edewit** [keycloak/keycloak-admin-ui#404]
when you navigate to `Client scopes` on the client details screen then switch the sub tab to `evaluate` then go to roles, you get the edit roles screen instead of the roles list.

**Comment by mfrances17** [comment]
this will also occur if you click the `Setup` subtab (or presumably any other subtab) and then click any of the other non-subtabs. 

this is because the URL that is being passed within KeycloakTabs appends the existing tab's subtab to the new URL, e.g. it goes from `/clientScopes/setup` to `/roles/setup`, which doesn't exist.
