### ISSUE TITLE
UI Changes from KEYCLOAK-14846

### ISSUE THREAD

**Issue by ssilvert** [keycloak/keycloak-admin-ui#687]
The UI logic from this PR needs to be reflected in the new admin console:
https://github.com/keycloak/keycloak/commit/1402d021deb014310027ba506e6cfa7686b315b4

The UI code is at the bottom of the PR.  Search on "/realm.js" and "realm-default-roles.html".

@jenny-s51 You and I will need to meet with the author, @vramik, and go over these changes.

**Comment by ssilvert** [comment]
Based on meeting with Vlasta, we need the following changes:

- Recognize default realm role.  Add help text so that user understands it is special.
- Do not allow default realm role to be deleted.
- Description for default realm role should be read only.
- Attributes tab should be hidden
- Users in Role tab should be hidden

**Comment by vramik** [comment]
For the reference:

- the documentation PR which was part of KEYCLOAK-14846: https://github.com/keycloak/keycloak-documentation/pull/1071
- link to docs: https://www.keycloak.org/docs/latest/server_admin/#_default_roles

**Comment by ssilvert** [comment]
Thanks.

**Comment by mfrances17** [comment]
@jenny-s51 Not exactly sure without seeing it in your code, but it sounds like you could just create a new type that combines RealmRepresentation and the missing props... something like (pseudocode):

type myRealmRepresentation = RealmRepresentation & {
    defaultRole?: {
        id: string;
        name: string;
        etc for all props
    }
}
And then use the myRealmRepresentation type instead of RealmRepresentation.

**Comment by jenny-s51** [comment]
Thank you @mfrances17 ! Great solution

**Comment by vramik** [comment]
Hey @jenny-s51, the issue seems to be no longer there, but I wanted to highlight `defaultRoles` vs `defaultRole` in `RealmRepresentation`. 

- `@Deprecated  protected List<String> defaultRoles;` : https://github.com/keycloak/keycloak/blob/master/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L104-L105 ... this was used previously before KEYCLOAK-14846
- `protected RoleRepresentation defaultRole;` : https://github.com/keycloak/keycloak/blob/master/core/src/main/java/org/keycloak/representations/idm/RealmRepresentation.java#L106 ... is used since KEYCLOAK-14846

**Comment by edewit** [comment]
@jenny-s51 can you make an issue for keycloak-nodejs-admin-client to update the `RealmRepresentation`?

**Comment by jenny-s51** [comment]
@edewit absolutely - done
